name: unit tests

on:
  push:
    branches:
      - main
      - pipeline-test
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
