name: Run pylint

on:
  push:
    branches:
      - main
      - add-pylint
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pylint and dependencies
        run: |
          python3.8 -m pip install --upgrade pip
          pip install pylint
      - name: Run pylint on *.py files
        run: |
          find . -name '*.py' -exec pylint {} \;
