name: Run pylint

on:
  push:
    branches:
      - main
      - add-pylint
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pylint
        run: apt install pylint
      - name: Run pylint on *.py files
        run: pylint ./*.py ./**/*.py
