name: unit tests for snowflake_connector 

on:
  push:
    branches:
      - pipeline-test
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: test 
        run: ls snowflake_connector
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - name: Install libs
        run: |
          python -m pip install --upgrade pip
          pip install -r snowflake_connector/requirements.txt
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - name: Unit test execution
        run: cd snowflake_connector && python3 -m unittest -v test_snowflake.py
        working-directory: ${{ env.GITHUB_WORKSPACE }}
